### PR TITLE
Cache Busting Scripts

### PR DESCRIPTION
**Pull request by seijihariki**
Some cache busting scripts and commit hooks

### CODE REVIEW

**Comment by seijihariki** [comment]
Forced push to clear all the test commits done to test Github actions stuff.

**Comment by zero01101** [comment]
so to start i apologize for being absent recently; our beloved dog loki passed away somewhat unexpectedly while we were asleep, and it's been pretty dire around here :( 

otherwise, face restore is an immediate "but of course" and thanks to your prior work on improving extensibility, barely needs anything even close to a review :) i also suspected my hacky resolution sync would come back to bite me one day... 

i honestly might need to apply some of this cache busting magic to some of my legacy employment repos that have some manual `blah.js?20160406-0001` kind of drudgery going on
lil bad pokerface

**Review by zero01101 — APPROVED** [review]

**Comment by seijihariki** [comment]
> so to start i apologize for being absent recently; our beloved dog loki passed away somewhat unexpectedly while we were asleep, and it's been pretty dire around here :( 

Yes, I saw your tweet yesterday. Sorry for your loss, he was the bestest of bois! Hope he is doing fine in dog heaven.

And you don't need feel any obligation to be active every single day! Just come back when things settle.

> otherwise, face restore is an immediate "but of course" and thanks to your prior work on improving extensibility, barely needs anything even close to a review :) i also suspected my hacky resolution sync would come back to bite me one day... 

Well, just some things to avoid duplicating code actually, in this case mainly wheel handling code.

> i honestly might need to apply some of this cache busting magic to some of my legacy employment repos that have some manual `blah.js?20160406-0001` kind of drudgery going on
> lil bad pokerface
> 

Well, it's MIT, so no problems whatsoever! And don't forget to setup the hooks on your machine!

**Comment by zero01101** [comment]
>Sorry for your loss, he was the bestest of bois! Hope he is doing fine in dog heaven.

<3 thank you greatly, he truly was.  my sister in law recently lost her sweet pup too so he's definitely got a best friend to play with on the rainbow bridge

>And don't forget to setup the hooks on your machine!

image
god github needs to just let me add custom emoji like slack lol

much obliged for the reminder lol 
image

**Comment by zero01101** [comment]
oh god it took me forever to realize what i needed to do in windows and i hate npm so much lol -_-

**Comment by zero01101** [comment]
sigh ok so it seems to be ignoring any non-staged files when i commit through sourcetree because i need a GUI like a tiny child, but hopefully those dumb pushes to prevent node_modules from getting the hash update treatment didn't break anything; i WAS going to put that in testing and get your 2nd opinion _but needed them to actually commit the readme lmao_ 

anyway i don't think that should _break_ anything but knowing me, someone's GPU will catch fire because of it

**Comment by seijihariki** [comment]
Yep, didn't notice that. Will push a quick patch to only add .html files directly to main.

**Comment by seijihariki** [comment]
Now only staged files are considered, and on commit only .html files are actually added automatically.

**Pull request merged**
