### PR TITLE
Custom select and (Very) simple settings page

### PR DESCRIPTION
**Pull request by seijihariki**
Custom select for easy model choosing and input now spans a vast area for easier canvas corner painting.

### CODE REVIEW

**Comment by zero01101** [comment]
oh, the new select list is fantastic, very select2-ish, and HOLY CRAP resizable canvas is like 99% of what i wanted with infinite anyway - i tried doing something KIND of like this forever ago but also tried to get it to sort of "dynamically" expand which you seem to also have discovered is, uh... nontrivial lol

this is NOT a bug report but just out of morbid curiosity, resolutions above 11k x 11k seem to stop drawing the checkboard background lol

also sorry about lack of further commentary on yesterday's patches; taking care of a sick dog here :( but as always, enormous thanks for all you're doing, this is magic <3

**Comment by seijihariki** [comment]
> oh, the new select list is fantastic, very select2-ish, and HOLY CRAP resizable canvas is like 99% of what i wanted with infinite anyway - i tried doing something KIND of like this forever ago but also tried to get it to sort of "dynamically" expand which you seem to also have discovered is, uh... nontrivial lol

Yeah, I actually have an idea to do this with less headaches regarding coordinate transforms. I will give it a tey in the next few days.

> this is NOT a bug report but just out of morbid curiosity, resolutions above 11k x 11k seem to stop drawing the checkboard background lol

Oh god, no idea. We still use the original checkervoard generation , but from what I recall, nothing in there should limit the canvas size. 

> also sorry about lack of further commentary on yesterday's patches; taking care of a sick dog here :( but as always, enormous thanks for all you're doing, this is magic <3

No worries whatsoever! I hope he gets better!

**Comment by seijihariki** [comment]
It should be fine to merge.

**Comment by zero01101** [comment]
>I hope he gets better!

❤🙏 very likewise, thanks; a few grand at the vet's already but he's a Good Boy so it's worth every penny :)  

>@seijihariki
[adds index 0 to image gen](https://github.com/zero01101/openOutpaint/pull/76/commits/0e6a5c8d4a6ca233b1051c820c87256b6648450c)

:o i didn't know i wanted this until i used this, this is marvelous

lol now i gotta update the wiki step-by-step i just pushed :D

**Pull request merged**
