### PR TITLE
Mostly Documentation and Development Tooling

### PR DESCRIPTION
**Pull request by seijihariki**
Some features for easy debugging/development, and jsdoc documentation/jsconfig.json for intellisense in IDEs:
image

For now, utils.js and commands.js are fully documented. Other are not.

### CODE REVIEW

**Review by zero01101 — COMMENTED** [review]
i _genuinely_ didn't know you could do this without typescript lol

**Review by zero01101 — COMMENTED** [review]
<3 oh this is fantastic, i just tested your overmask canvas suggestion and it dumped out like 20 tabs of in-progress masks
...i just realized this isn't attaching these comments to specific commits/files lol

**Comment by zero01101** [comment]
the jsdocs are marvelous and i'm a huge fan, guards are super clever and i promise you'll make use of them long before i do ;) as mentioned, i selfishly love the downloadCanvas() to new tab bit and i've got the MDN tab on proxy open right now because i've obviously never used it before :D not sure why you put this back to draft, this all looks fantastic, alongside the wiki page you put up too, i mean good heavens

**Comment by seijihariki** [comment]
> i _genuinely_ didn't know you could do this without typescript lol

I mean, it's not really 'without' typescript, but I get what you mean!

> the jsdocs are marvelous and i'm a huge fan, guards are super clever and i promise you'll make use of them long before i do ;) as mentioned, i selfishly love the downloadCanvas() to new tab bit and i've got the MDN tab on proxy open right now because i've obviously never used it before :D not sure why you put this back to draft, this all looks fantastic, alongside the wiki page you put up too, i mean good heavens

I actually drafted this pull before submitting 7c7352a0ebd431b7a2b59024915bf86daf2984a9 and simply forgot completely to undraft it.

I assume then I can merge it directly!

**Pull request merged**
