### PR TITLE
mouse input handler - input.js - proper solid mask

### PR DESCRIPTION
**Pull request by seijihariki**
This is quite an extensive pull request.

Some changes: 
 - Added input.js for handling mouse input:
     - It exposes easy-to-use events, such as ondragstart, ondoubleclick, etc, and handles left, right, and middle mouse buttons. It is much easier to implement new features using this abstraction, and it handles canvas coordinates by itself. the plan is that when we implement the infinite canvas, it also should perform automatic translation of coordinates according to viewport.
     - Example code for mask implementation:
image
    - We can see that it becomes much simpler to implement, without boilerplate code to track previous mouse states and whatnot. 
 - The mask now uses a solid color instead of a transparent one; the mask layer itself is now semi-transparent to allow viewing through the mask. The mask's opacity shouldn't make a difference for stable diffusion, and so the mask should reflect that:
 Before: 
Peek 2022-11-21 00-11
Now:
Peek 2022-11-21 00-13

The new mask implementation should make the implementation of a mask history (undo/redo) to be quite simple to achieve, using the onpaintstart and onpaintend events.

Little by little, I will work on migrating other functionality to the new input system. It will be hard to work much on this during the week, but I plan to extend the input.js to allow for keyboard inputs and add shortcut support (for now mainly to use on undo/redo stuff).

### CODE REVIEW

**Comment by seijihariki** [comment]
Middle mouse support was added more for a "why not" reason, and it wasn't really difficult. It may be useful in the future for implementing viewport drag for infinite canvas.

**Comment by zero01101** [comment]
good heavens, yeah, extensive is definitely the right word for it lol; i've already glanced at a few sections i don't immediately understand which was To Be Expected i suppose ;) will give this a more thorough overview and merge it once i get that "aha" moment 

>It will be hard to work much on this during the week

WOW holy crap no worries at _all_, you generous wonderful people throwing these marvelous PRs at me have already probably written more of this than i have; by all means feel no pressure to keep up your heroic pace so far lol

**Review by Kalekki — APPROVED** [review]
This is great stuff

**Comment by seijihariki** [comment]
> good heavens, yeah, extensive is definitely the right word for it lol; i've already glanced at a few sections i don't immediately understand which was To Be Expected i suppose ;) will give this a more thorough overview and merge it once i get that "aha" moment. as always, huge thanks!

No problems! You can take your time! It's more of a "quality of life" thing for simpler mouse input usage. The last commit (459bc1b) has another usage example for the input lib.

> WOW holy crap no worries at _all_, you generous wonderful people throwing these marvelous PRs at me have already probably written more of this than i have; by all means feel no pressure to keep up your heroic pace so far lol

No pressure whatsoever, I've actually been searching for an easy alternative for sd-infinity that used automatic1111's API - I even modified sd-infinity with a drop-in implementation to try using it with the API - and this project seems to have great potential to be what I was searching for. That's why I'm so excited to help!

**Comment by zero01101** [comment]
so i absolutely meant it when i said i was [terrible](https://github.com/zero01101/openOutpaint#terrible) at JS lol; like, my familiarity with the observer pattern was pretty much the same as my familiarity with being filthy rich: i know it exists and other people probably have a better idea of what to do with it :) 

that being said, going through input.js is the most luck i've had with simply understanding the concept and how it works, but things like https://github.com/zero01101/openOutpaint/pull/22/files#diff-1d2688bdcb2d67f9bfc101724ba505e287b0c8da9c69c933062dc22a26163cf3R150 are still black magic as far as i'm concerned :D

anyway, beyond future usability/generally making this whole shebang more extensible and less rickety, the educational aspect of your work is huge and i once again can't thank you enough :)

**Comment by seijihariki** [comment]
> that being said, going through input.js is the most luck i've had with simply understanding the concept and how it works, but things like https://github.com/zero01101/openOutpaint/pull/22/files#diff-1d2688bdcb2d67f9bfc101724ba505e287b0c8da9c69c933062dc22a26163cf3R150 are still black magic as far as i'm concerned :D

Oh, that is just a quick (and admittedly kind of ugly) way to check if something is not null and run it!

Basically, equivalent to
`if (buttons[evn.button]) buttons[evn.button]()`
It's getting `buttons[evn.button]` and running the function if it exists. That is for the case when a mouse is used that has, for example, a third or fourth button (other than left, middle, right). It will try indexing the array and fail gracefully without throwing an exception.

**Pull request merged**
