### PR TITLE
Add ability to mark images

### PR DESCRIPTION
**Pull request by ribawaja**
Added a "\*" button to the image select menu (keyboard shortcut: "\*") which marks the current image.

Scroll through only the images which have been marked by using Shift key + existing image navigation control, e.g. Shift + mouse scroll up/down, Shift + click "<" or ">" buttons on image select menu, or Shift + "<" or ">"  keyboard shortcuts.

The image index text displays the marked indicator, e.g. "\*6/54" indicates that the current image (6) is marked.
Pressing "\*" while on a marked image will unmark the image.
Marked image indices are correctly adjusted when images are removed from the list with "-".

### CODE REVIEW

**Comment by zero01101** [comment]
apologies that i haven't gotten a chance to check this out yet D: glancing over the code seemed perfectly fine and scout's honor i'll give it a proper once over, uh, soonish

**Comment by ribawaja** [comment]
No worries! Feel free to suggest changes to the interface or behavior.
I'm playing around with it now, seems to work nicely, saves time.

**Comment by zero01101** [comment]
apologies that it took so long!

**Comment by ribawaja** [comment]
Thanks! And thanks for making such an awesome tool.

**Pull request merged**
