### PR TITLE
Pull Request for 2022-12-12

### PR DESCRIPTION
**Pull request by seijihariki**
Just another draft for 12-12. For now, has migration from local storage in stamp.js to IndexedDB for more storage space.

### CODE REVIEW

**Comment by seijihariki** [comment]
Fix single pixel upset in cropCanvas bounding box. We have had this problem before, but I thought it was just rounding errors and just added a padding to circumvent the problem. now should have been corrected for the most part.
[Reference report on reddit](https://www.reddit.com/r/StableDiffusion/comments/zi2nr9/comment/izva8nm/)

**Comment by seijihariki** [comment]
Prompt interface overhaul

**Comment by zero01101** [comment]
good lord man, do you ever sleep? this is magnificent stuff, fantastically usable; i'm still trying to make sure the tiny bits of making multiple sliders update in concert while you're over here implementing outright magic <3 

it's uh pretty clear you're in a different league of software developer than i can even pretend to be, and that you're taking this silly little project _much_ more seriously than i am :D it's hugely appreciated and i hope you're not feeling like i'm just letting you do all the work even though that's kind of what's happening :|

**Comment by seijihariki** [comment]
> good lord man, do you ever sleep? this is magnificent stuff, fantastically usable; i'm still trying to make sure the tiny bits of making multiple sliders update in concert all play nice while you're over here implementing outright magic <3

Didn't work so much on the project today, actually. The idea for the history just popped in my head and I wanted to see it done! Most other things were half-done from yesterday.

> it's uh pretty clear you're in a different league of software developer than i can even pretend to be, and that you're taking this silly little project _much_ more seriously than i am :D it's hugely appreciated and i hope you're not feeling like i'm just letting you do all the work even though that's kind of what's happening :|

I feel like that's an exaggeration, considering I currently am not even a developer, but I do like developing some personal projects, so thanks for the praise!

Well, considering this, I assume it's okay to merge into main. Will also close related issues.

**Comment by zero01101** [comment]
>Didn't work so much on the project today, actually. 

pffft you've still put more into it within 48 hours than i have in two weeks 🥇 

>I currently am not even a developer

?!?!?!???!!?!?!??! i'm sorry, i believe i have several thousand lines of open-source code evidence to the contrary my friend ;)  

meanwhile i'm employed in the Technology Sector and getting absolutely mopped with these new concepts and abstractions and i feel like 
image
lol

>Well, considering this, I assume it's okay to merge into main. 

oh man, i invited you as a direct collaborator specifically so you could just merge things you wanted to <3 by ALL means, feel free!  as always, my most genuine thanks for everything

**Pull request merged**
