### PR TITLE
Just Some QOL and bugfixes

### PR DESCRIPTION
**Pull request by seijihariki**
Draft pull request for 2022-12-11. For now, only has an extra network status indicator for detecting disabled --api flag.

### CODE REVIEW

**Comment by seijihariki** [comment]
This last one seems to be a prevalent issue on windows machines with ipv6 configured.

The server ends up on ipv6-only territory due to some dual-stack weirdness on windows systems:


https://bugs.python.org/issue39211

This is an attempt to fix by listening on 0.0.0.0. Someone with the issue should test this solution, and if it does not work, we will need to bind to loopback.

**Comment by zero01101** [comment]
>multiselect now also custom autocomplete

you just had to go and deprecate the wiki immediately, didn't you ;)  

all looks great; wonder if we should add the specific address bind on the .sh launch script too just for parity?  

thanks again as always!

**Comment by seijihariki** [comment]
> > multiselect now also custom autocomplete
> 
> you just had to go and deprecate the wiki immediately, didn't you ;)
> 
> all looks great; wonder if we should add the specific address bind on the .sh launch script too just for parity?
> 
> thanks again as always!

Hope we don't have to do that! Just give these last changes a look and you can merge!

**Comment by zero01101** [comment]
mighty handy little buttons!

**Pull request merged**
