### PR TITLE
WebUI Extension Fixes

### PR DESCRIPTION
**Pull request by seijihariki**
[Firefox Bug #733698](https://bugzilla.mozilla.org/show_bug.cgi?id=733698) Workaround for WebUI extension.

From gist https://gist.github.com/subzey/2030480.

Fixes manual dream selection required described on https://github.com/zero01101/openOutpaint-webUI-extension/issues/1

### CODE REVIEW

**Comment by zero01101** [comment]
manually tested in extension's index.js, seems to work jim dandy 👍

**Comment by seijihariki** [comment]
Should be fine. To test with the extension, go to the app directory in the webui extension and change to testing branch.

**Comment by seijihariki** [comment]
Still requires a refresh button and proper scaling of the iframe.

**Comment by seijihariki** [comment]
Prefixing local storage values with openOutpaint/* would be optimal.

**Comment by seijihariki** [comment]
Will be merging. We can fix extra things later.

**Pull request merged**
