### PR TITLE
2022-12-13 Testing Pull

### PR DESCRIPTION
**Pull request by seijihariki**
For now, changes default to sync cursor and resolution. Also adds generation resolution (albeit smaller) to cursor render to make it more explicit.

### CODE REVIEW

**Comment by seijihariki** [comment]
Add drag area selection for dream generation. There is some duplicate code, but will handle that another day. Supposedly partially solves #91.

**Comment by zero01101** [comment]
good heavens the drag-arbitrary-area dream tool is like 4x nicer than i was imagining given that i suggested an entirely different tool

i've actually already caught the secondary render resolution indicator in action a few times, saving me after i accidentally left sync off when testing #99 lol  

seriously though 100% delightful 👍

**Comment by seijihariki** [comment]
Fixed (supposedly) #99. Let's wait for responses to #99 and #93 to merge this pull request.

**Comment by zero01101** [comment]
new changes here are wonderful as always for what it's worth 👍

**Comment by seijihariki** [comment]
> new changes here are wonderful as always for what it's worth +1

Yeah, but this pull is dragging a bit! Today (maybe tonight) will try doing the keep mask Gaussian blur and merge this thing

**Comment by seijihariki** [comment]
@zero01101 Do you think it's too big of a change? (this last commit)

**Comment by seijihariki** [comment]
Solving the incompatibility in another way would likely require modifying the viewport to use world coordinates for dragging the canvas, which is... How could I say... Hard.

**Comment by zero01101** [comment]
>Yeah, but this pull is dragging a bit! 
i'm in no hurry - this is still a silly little gizmo toy project to me, i'm just thrilled other people use it :) i'll likely be somewhat predisposed for the near foreseeable anyhow :/ 

>Do you think it's too big of a change? (this last commit)

i unfortunately won't get a chance to even try it for hours, will check this evening, a quick glance doesn't appear to be TOO overwhelming however and knowing you, it's pretty sure to be masterful :) 

actually, i just pushed some changes i failed to last night; you might want to give them a once-over and make sure i didn't ruin something inadvertently since i had to modify the `_dream()` output :|

**Comment by zero01101** [comment]
hm, seems something's firing `_dream_onwheel` twice when changing reticle size...

**Comment by seijihariki** [comment]
> hm, seems something's firing `_dream_onwheel` twice when changing reticle size...  seems to have been introduced with https://github.com/zero01101/openOutpaint/pull/100/commits/9a81946eef6a80885afe7e4752aa120187685fd2 

Will give this a look.

Yeah, about the Ctrl for pan was mostly because it would be quite difficult to allow it to work as is without messing with other things and then I made up the consistency argument after that.

But the more I think about it, it seems more like a logical thing to do.

**Comment by zero01101** [comment]
lol yeah i'm trying to figure out what causes it too, stepping through is weird; like the new swheel handler picks up first but fails to kick in as expected but i can't see _what's_ causing the normal wheel handler to get too excited

**Comment by seijihariki** [comment]
There shouldn't be anything that could duplicate an event, I think. I'm via cellphone for now, but I can look into it a bit.

**Comment by zero01101** [comment]
oh geez, of course no hurries at all lol, just finally getting a chance to check out _your_ commits and noticed that so i started going back through each commit to see where it started :D

**Comment by seijihariki** [comment]
Got home, found the issue. (Duplicate listener registered)
image

**Comment by zero01101** [comment]
lmao and here i was THIS CLOSE to saying "ok ok ok i found something; look in current branch there's 3 handlers registered and one looks duplicated" but you had to be just a bit faster ;) 
image

confirmed fixed :D

**Comment by seijihariki** [comment]
> lmao and here i was THIS CLOSE to saying "ok ok ok i found something; look in current branch there's 3 handlers registered and one looks duplicated" but you had to be just a bit faster ;) image
> 
> confirmed fixed :D
> 
> [edit]
> 
> i JUST noticed that those are three different handlers and am now questioning my ability to read

Haha yeah, I used the ol' debugging prints to check for wheel events specifically:

image

**Comment by zero01101** [comment]
working on wiki here and there, will also version bump main when that's all set.  my sincerest gratitude as always :)

**Comment by seijihariki** [comment]
Okay, thanks! Created discussion to notify people about the pan control changes.

**Comment by zero01101** [comment]
good plan; i'll also put a callout in the readme features about that 👍

**Pull request merged**
