### PR TITLE
Win hooks - basics

### PR DESCRIPTION
**Pull request by seijihariki**
Attempts to write some tests on #132.

Trying to meddle with some LF/CRLF quirks, as those change the file hashes used for cache busting.

### CODE REVIEW

**Comment by zero01101** [comment]
lmao how DARE you, i was writing .bat scripts myself and then you're all like "i don't even manually use lint script" and i'm all "well fine then, i guess i won't either" but here you are with .bat scripts

**Comment by seijihariki** [comment]
Haha! I still don't use manual lint scripts, but git hooks are an entirely different story, as they pertain to actual cache busting requirements!

You may see that even here we have no lint.bat or lint.ps1 in sight.

**Comment by seijihariki** [comment]
If you could test this and check that everything works alright (hashes are calculated okay and everything).

**Comment by seijihariki** [comment]
And good one on reminding me of the .bat files. We are mostly using .ps1 files, the bat was just some early attempts. Will be removing the .bat.

**Comment by zero01101** [comment]
added some tiny adjustments, should ignore `node_modules` directory now and call the .ps1 script from pre-commit :) seemed to hash identically to .sh script 👍

**Review by zero01101 — APPROVED** [review]

**Comment by seijihariki** [comment]
Okay, will be merging this into main!

**Pull request merged**
