### PR TITLE
Add tool for img2img

### PR DESCRIPTION
**Pull request by seijihariki**
This pull request adds a tool for performing img2img, and refactors the other tools to have less duplicate code. In img2img, masking works in reverse (masked areas stay). The img2img tool supports a feature that I am calling border masking (we can think of a better name later), which is basically that when the img2img request is sent, a mask is added on the borders of the image, making it not lose coherence with the rest of the canvas:
Original:
image
Without border masking:
image
With border masking:
image

And you can customize the mask size:
image

### CODE REVIEW

**Comment by zero01101** [comment]
good GOD i love this so much; i actually noticed however that https://github.com/zero01101/openOutpaint/pull/37/files#diff-de12f78f94aec22c1af7fbc344b03e9050f44f018e09b67c391eea6d23128f49R176 should be `dream(bb.x, bb.y, request, {method: "img2img", stopMarching, bb});`, otherwise your oh-my-god-this-is-so-fun-i-can't-stop-playing-with-it bordermasking is like my favorite surprise feature i never knew i needed <3 

i mean just LOOK at this idiocy i'm able to mash out  
2022-11-23 03 45 25 openOutpaint image

anyhoo, beyond that tiny `dream()` modification, i noticed that when typing in the prompt fields that the tools would bounce between active/inactive by keyboard shortcut - any way to prevent those from firing if either prompt field has active focus?

**Comment by zero01101** [comment]
holy crap bad keyboard no no no do not close very good pull request

**Comment by seijihariki** [comment]
> good GOD i love this so much; i actually noticed however that https://github.com/zero01101/openOutpaint/pull/37/files#diff-de12f78f94aec22c1af7fbc344b03e9050f44f018e09b67c391eea6d23128f49R176 should be `dream(bb.x, bb.y, request, {method: "img2img", stopMarching, bb});` _(i think)_, otherwise your oh-my-god-this-is-so-fun-i-can't-stop-playing-with-it bordermasking is like my favorite surprise feature i never knew i needed <3
Oh, it seems I have this exact fix locally; I forgot to commit the changes, let me send it here!

> //todo learn how people do that very attractive styled inline code block quote i've seen in other comments
> 
> i mean just LOOK at this idiocy i'm able to mash out 2022-11-23 03 45 25 openOutpaint image
Haha! Yeah, I wanted img2img because of the flexibility it gives to edit things.

> anyhoo, beyond that tiny `dream()` modification, i noticed that when typing in the prompt fields that the tools would bounce between active/inactive by keyboard shortcut - any way to prevent those from firing if either prompt field has active focus?
I know this is actually a problem, and I though I fixed it in this exact pull request... My attempt is the only change on input.js on 8e6d72cd93b52713440a6f00f88c680d89ad8ed4

Testing now, it seems not to be fixed; Let me give it a look.

> also, am i correct in thinking this includes/supersedes pr 36?
Yes, this branch is based on the toolbar branch.

**Comment by seijihariki** [comment]
Fixed the keyboard issue. Had to check for tag names manually and clear input focus on canvas hover.

**Comment by seijihariki** [comment]
Other than that, I actually noticed that erase history is kinda buggy; I probably should have a look at that.

**Comment by SMUsamaShah** [comment]
This mask needs to be fuzzy probably, or leak a bit outside or to be a gradient to avoid the seams. Looking at the arm in above image for example.

**Comment by seijihariki** [comment]
I think the seam issue is during outpainting, actually, and that's what overmasking helps with. The thing is, I think the repo has had so many updates recently that merging the overmasking branch into it would basically require a full rewrite.

**Comment by zero01101** [comment]
>Yes, this branch is based on the toolbar branch.

awesome; i'll close PR 36 then.  keyboard shortcut vs prompt confirmed fixed as well, much obliged :) 

>Other than that, I actually noticed that erase history is kinda buggy; I probably should have a look at that.

hah! i noticed that last night and actually made a [comment](https://github.com/zero01101/openOutpaint/pull/31#issuecomment-1324530220) on the closed history palette PR which is pretty dumb in hindsight lol 

unfortunately it seems to have decided to evolve into a different bug as these things have a tendency to do ;) 

steps to reproduce:  
- dream an image
- erase a bit of it 
- undo erase 
- dream a new image

this results in a referenceerror due to "entry is not defined" on `history.js:33` and the last entry on the palette becomes unclickable, dumping selection to the 2nd entry titled "erase" but results in the image dream

image

> The thing is, I think the repo has had so many updates recently that merging the overmasking branch into it would basically require a full rewrite.

:badpokerface:  

look i warned everyone i'm sort of an idiot and i proudly stand by that, so uhhh i was having so much fun with border masking that i completely failed to even notice that overmasking no longer existed until i tried a regular outpaint and said HEY WHAT'S THAT SEAM DOING THERE lol  

i already have a stash against this branch that will clumsily puke an updated-to-comply-with- back into `dream.js` and @seijihariki will probably have good cause to punch me square in the jaw for fouling up this very extensible and modular code with my first-day for loops, but i just really like overmasking ok :D 

_COMPLETELY_ agreed it surely needs a rewrite overall, i'm just an idiot as mentioned ;)

**Comment by zero01101** [comment]
sigh of course i made a merge conflict :( terribly sorry for additional annoyance, wanted to get some of this in motion while i was on lunch "break" lol

**Comment by seijihariki** [comment]
Fixed merge conflicts; no problem!

History now actually fixed; It seems it was working but after testing and before committing, I put a pretty "console.log" message that broke it.

**Comment by zero01101** [comment]
_delicious_

**Comment by zero01101** [comment]
also 
>but after testing and before committing, I put a pretty "console.log" message that broke it.

this is amazing and heartbreaking and could be a fantastic example of "well because THIS kind of thing happens" when people ask why i am bad at javascript and why haven't i gotten better at it yet :D

**Comment by SMUsamaShah** [comment]
Hey @seijihariki please give this a try. I feel like your border masking idea for img2img should work on non-inpainting models too.

**Pull request merged**
