### PR TITLE
Prototype (though pretty stable) of a layer management system

### PR DESCRIPTION
**Pull request by seijihariki**
It still has no layer deletion because that would probably break history. (Need to add a command for layer deletion and undo to not corrupt it)

Operations that used images to send elsewhere (canvas download, dream tools)  now use visible information as data. You can hide layers and do all of that. Select tool still only affects active layer. Renaming layers is by double-click on layer name (will probably do the same to resource manager at some point).

Merge layers also requires layer deletion, so not yet. Grouping shouldn't be too hard to implement, but will be quite a chore.

Added option to render canvases smoothly or pixelated to have more pixel-to-pixel control (looks terrible from afar).

Fix: Resolved some issues with clicking the eyedropper, and fixed resource persistence not keeping images for more than one page reload.

Optimization: A lot of the rendering of cursors is now done on an overlay canvas not tied to the dynamic layer system. We don't really need all those functionalities for cursors, and these cursors should not scale with the zoom (becoming pixelated); Some things are still there, but select and dream progress should also be migrated to the new overlay (uiCanvas and uiCtx).

### CODE REVIEW

**Comment by zero01101** [comment]
omg dreams on new layers even sample other layers for coherence, this is delicious

i've immediately started thinking about using like difference  globalcompositeoperation for some kind of magical automatic identical-pixel-masks for new layers

**Comment by seijihariki** [comment]
After some more testing, it seems gradients indeed do work - the seam moves a bit, and seems less noticeable. Not really objective testing, but I seem to be consistently getting better results. But masks of a solid gray color do not seem to do much.

This is a first gradient-based tool, as suggested on https://github.com/zero01101/openOutpaint/discussions/28#discussion-4588449.

Sorry to @SMUsamaShah, seems my testing was not throughout enough.

**Comment by zero01101** [comment]
see like yeah, why didn't my very old overmask with graidents tests work like this >:(

**Comment by seijihariki** [comment]
Fixed interrogate to use new layer system, added error handling and green marching ants to show it's doing something.

**Comment by seijihariki** [comment]
> omg dreams on new layers even sample other layers for coherence, this is delicious
> 
> i've immediately started thinking about using like difference globalcompositeoperation for some kind of magical automatic identical-pixel-masks for new layers

Not sure what exactly is your plan, but its sounds exciting!


> see like yeah, why didn't my very old overmask with graidents tests work like this >:(

Seems there are some kinda specific circumstances where gradients are actually useful. I think what we need to do is to implement each tool with gradients and check if they work or not for that purpose.

Took a bit to answer because most comments here were done in a hurry.

**Comment by seijihariki** [comment]
I'm thinking (for now my priority is full layer support) we could maybe implement a gradient profile tool instead of a simple slider checkbox. (could be handy for some interesting things going forward)

This element would be used to edit gradient stop sequences. A reference fpr such a tool would be the color curve editing tool in photoshop/gimp. As we are using only the linear gradient provided by the canvas context, we don't need to implement those smooth lines, just a simple zigzag line would be enough probably.

**Comment by seijihariki** [comment]
> having even a minimally functional gradient editor is still a wild amount of powerful flexibility i'd say, and i'd also bet you're spot on regarding limited usefulness of gradients in specific use cases, particularly with the small pixel counts of how overmask is applied

Was just thinking... Wouldn't just a blur() filter for drawing image masks be enough for some initial testing of gradient on dream()?

We wouldn't have much of the cool gradient stop controls, but should be good enough for some basic testing.

**Comment by zero01101** [comment]
>Was just thinking... Wouldn't just a blur() filter for drawing image masks be enough for some initial testing of gradient on dream()?

see like i tried just setting the canvas filter to blur() in early overmask tests and it was _catastrophic_ for coherence with existing imagery, but i'd bet on the fact that i applied it wildly incorrectly and it failing was my fault lol 

>One more thing, I feel this should be one of the last big architecture updates that messes up a lot of things.

lmao you stoppit <3 this stuff is absolutely fantastic and this app wouldn't be a fraction of what it is now without your work, and it's hugely appreciated :D

**Comment by seijihariki** [comment]
> > Was just thinking... Wouldn't just a blur() filter for drawing image masks be enough for some initial testing of gradient on dream()?
> 
> see like i tried just setting the canvas filter to blur() in early overmask tests and it was _catastrophic_ for coherence with existing imagery, but i'd bet on the fact that i applied it wildly incorrectly and it failing was my fault lol

I mean, there is not much that can go wrong regarding applying blur() filters, so there shouldn't be anything that could really go wrong with that... Now that I think about it, the coherence problem was because of part of the black (transparent) areas being inside non-fully opaque masks, decreasing SD's capability of replacing black stripes. Maybe using shadow() could work better, to keep the full transparent areas, with some bleeding into the images.

Also, regarding
> So I think this would be an interesting time to get some more hands in the project.

I spoke with a mod ([u/SandCheezy](https://www.reddit.com/user/SandCheezy/)) from the [r/StableDiffusion](https://www.reddit.com/r/StableDiffusion/) Subreddit. It seems it would not be a problem to post about the project there again to show off what we have now after 20 days! But it's your project, so you decide what to do.

**Comment by seijihariki** [comment]
> oh, on this, yeah, i had grand intentions of making an actually useful wiki with actual feature level documentation but then the whole Life Getting In The Way thing happened of course; i still plan to put that together this weekend fingers crossed 

That would be great! We do have now quite an assortment of features and different tools that could be a bit overwhelming for new users. 

> lmao that's kind of ironically super-appreciated since i was sort of also thinking about reposting it over last weekend but then got cold feet thinking it'd be spammy, plus invokeAI sorta had all the momentum at the moment 

Yeah, was kind of afraid of the same thing. And yes, InvokeAI was really in the spotlight for the week. Now i think the timing is okay. We could even try taking some inspiration in InvokeAI features maybe.

> oh i beg to differ, i see the numbers ;) 
> image

Oh, contribution is not only numbers! And most of those probably are probably just moving stuff around to make it less monolythic. 

> working on readme updates right now since those are really stream-of-consciousness and kind of sarcastic :) otherwise as mentioned, thank you enormously! 
> 

Great work on the readme! Was thinking maybe a short quickstart should be higher up in the document, actually. A very basic "git pull then run the script and open localhost" kind of thing.

**Comment by zero01101** [comment]
yeah, the readme is gonna go on a crash diet and get some serious "usability" changes  with the actual documentation wiki i _promise_ i'm gonna make for people who don't speak my particular dialect of ADHD-addled sarcastic venom :D 

i'll likely wait until the weekend-ish to repost to r/stablediffusion just off a basis of "i think that's when traffic is highest" lol, and i gotta admit to being pretty weak at self-promotion, but seriously the absolutely ridiculous amount of new features here warrants another call to attention i feel :D

**Pull request merged**
